server:
  port: 8088
  servlet:
    context-path: /marketing
  tomcat:
    max-swallow-size: -1
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: marketing
  profiles:
    active: local

springfox:
  documentation:
    swagger:
      v2:
        path: /marketing/v2/api-docs